dist: xenial
language: python
sudo: true
python:
- 3.6
- 3.7
- 3.8
env:
- CONNECT_TO_AWS=FALSE
before_install:
- sudo apt-get install -y ruby-coveralls
install:
- |
  travis_retry pip install -r requirements-to-freeze.txt
before_script:
- make lint
script:
- make test
after_success:
  - coveralls