dist: xenial
language: python
sudo: false
python:
- 3.6
- 3.7
env:
- CONNECT_TO_AWS=NO
before_install:
- sudo apt-get install -y ruby-coveralls
install:
- make lint
script:
- make test
after_success:
  - coveralls